import os
import glob
import json
from moviepy.editor import ColorClip, AudioFileClip, TextClip, CompositeVideoClip

AUDIO_FOLDER = "audio"
OUTPUT_PATH = "output_video.mp4"

# 1. Load dynamic tracking setup
if not os.path.exists("current_matchup.json"):
    print("❌ ERROR: current_matchup.json not found!")
    exit(1)

with open("current_matchup.json", "r") as f:
    matchup_data = json.load(f)

matchup_title = matchup_data["title"]
lines = matchup_data["script"]
print(f"🎬 Compiling layout video frame asset for concept: {matchup_title}")

# 2. Check for the audio voice file safely
audio_files = glob.glob(os.path.join(AUDIO_FOLDER, "*.mp3"))
if not audio_files:
    print("❌ CRITICAL ERROR: audio/voice.mp3 was not generated by generate.py!")
    exit(1)

audio_files.sort(key=os.path.getmtime, reverse=True)
AUDIO_FILE = audio_files[0]
audio_clip = AudioFileClip(AUDIO_FILE)

print(f"🎙️ Connected to sound clip: {AUDIO_FILE} | Duration: {audio_clip.duration:.2f}s")

# 3. Build a gorgeous, safe, keyless high-contrast canvas (Ultra stable mobile layout)
# Dark aesthetic background ensures yellow and white captions pop out beautifully on TikTok/Shorts feeds
video_clip = ColorClip(size=(1080, 1920), color=(15, 15, 22)).set_duration(audio_clip.duration)

# 4. Generate timing-matched caption clips
subtitle_clips = []
total_lines = len(lines)
duration_per_line = audio_clip.duration / total_lines

# Add a permanent dynamic title frame at the top center of the screen
try:
    title_clip = TextClip(
        matchup_title.upper(),
        fontsize=58,
        color='cyan',
        font='Arial-Bold',
        method='caption',
        size=(1080 - 100, None)
    ).set_duration(audio_clip.duration).set_pos(('center', 250))
    subtitle_clips.append(title_clip)
except Exception as title_err:
    print(f"Title layout notice: {title_err}")

# Loop through the sentences and map them out chronologically
for i, line in enumerate(lines):
    start_time = i * duration_per_line
    try:
        txt_clip = TextClip(
            line, 
            fontsize=52, 
            color='yellow', 
            font='Arial-Bold', 
            method='caption', 
            size=(1080 - 160, None)
        )
        txt_clip = txt_clip.set_start(start_time).set_duration(duration_per_line).set_pos('center')
        subtitle_clips.append(txt_clip)
    except Exception as text_error:
        print(f"Subtitle clip warning at line {i}: {text_error}")

# 5. Composite and Render final MP4 format video
if subtitle_clips:
    final_video = CompositeVideoClip([video_clip] + subtitle_clips).set_audio(audio_clip)
else:
    final_video = video_clip.set_audio(audio_clip)

final_video.write_videofile(
    OUTPUT_PATH, 
    fps=30, 
    codec="libx264", 
    audio_codec="aac",
    temp_audiofile="temp-audio.m4a",
    remove_temp=True
)
print(f"✅ Video engine run completed successfully! Output file: {OUTPUT_PATH}")
