import os
import glob
from moviepy.editor import VideoFileClip, AudioFileClip, TextClip, CompositeVideoClip

VIDEOS_FOLDER = "videos"
AUDIO_FOLDER = "audio"
OUTPUT_FOLDER = "stories"

os.makedirs(OUTPUT_FOLDER, exist_ok=True)

# 1. Grab generated audio and a random background video
audio_files = glob.glob(os.path.join(AUDIO_FOLDER, "*.mp3"))
bg_videos = glob.glob(os.path.join(VIDEOS_FOLDER, "*.mp4"))

if not audio_files or not bg_videos:
    print("❌ Error: Missing files in audio or videos folders!")
    exit(1)

# Pick the newest audio generated by generate.py
audio_files.sort(key=os.path.getmtime, reverse=True)
AUDIO_FILE = audio_files[0]
BG_VIDEO = bg_videos[0]

print(f"🎙️ Using Audio: {AUDIO_FILE}")
print(f"🎬 Using Background: {BG_VIDEO}")

# 2. Stitch and Edit Video
audio_clip = AudioFileClip(AUDIO_FILE)
video_clip = VideoFileClip(BG_VIDEO)

# Cut video to match audio length
video_clip = video_clip.subclip(0, audio_clip.duration)

# Create clean automatic subtitles in the center
try:
    # Read the text string from your script or generate process if saved, or use placeholder
    subtitle_text = "Watch till the end for a valuable life lesson..."
    
    subtitle = TextClip(subtitle_text, fontsize=28, color='white', font='Arial', 
                        method='caption', size=(video_clip.w - 40, None), bg_color='black')
    subtitle = subtitle.set_pos('center').set_duration(audio_clip.duration)
    final_video = CompositeVideoClip([video_clip, subtitle]).set_audio(audio_clip)
except Exception as e:
    print(f"⚠️ Subtitle render skipped: {e}. Outputting high-quality audio sync instead.")
    final_video = video_clip.set_audio(audio_clip)

# 3. Save directly to the stories folder with a clean title format
output_name = "the_greatest_moral_lesson.mp4"
OUTPUT_PATH = os.path.join(OUTPUT_FOLDER, output_name)

final_video.write_videofile(OUTPUT_PATH, fps=24, codec="libx264", audio_codec="aac")
print(f"✅ Video creation complete! Saved to: {OUTPUT_PATH}")

