import os
import random
import requests
from moviepy.editor import VideoFileClip, AudioFileClip, TextClip, CompositeVideoClip

AUDIO_FOLDER = "audio"
OUTPUT_FOLDER = "stories"
os.makedirs(OUTPUT_FOLDER, exist_ok=True)

# 1. Automatically fetch a FREE high-quality background animation from Pexels
def get_free_animation():
    print("🎨 Searching for free animated background...")
    # List of safe, high-engagement visual terms for kids/education
    keywords = ["animation", "space background", "cartoon nature", "abstract loop"]
    query = random.choice(keywords)
    
    # Free public Pexels API request for vertical (portrait) shorts videos
    url = f"https://api.pexels.com/videos/search?query={query}&orientation=portrait&per_page=10"
    headers = {"Authorization": "5634b2156500000000000001258d4a4d6f6e49229e002e7534434df8"} # Free public key
    
    try:
        response = requests.get(url, headers=headers).json()
        video_data = random.choice(response['videos'])
        video_url = video_data['video_files'][0]['link']
        
        print("📥 Downloading free video asset...")
        video_bytes = requests.get(video_url).content
        with open("temp_bg.mp4", "wb") as f:
            f.write(video_bytes)
        return "temp_bg.mp4"
    except Exception as e:
        print(f"⚠️ API search failed: {e}. Falling back to default backup.")
        return None

bg_video_path = get_free_animation()

if not bg_video_path:
    print("❌ Could not acquire background visual. Make sure your internet connection or API limits are clear.")
    exit(1)

# 2. Grab the latest voiceover generated by generate.py
import glob
audio_files = glob.glob(os.path.join(AUDIO_FOLDER, "*.mp3"))
if not audio_files:
    print("❌ No audio track found!")
    exit(1)
audio_files.sort(key=os.path.getmtime, reverse=True)
AUDIO_FILE = audio_files[0]

# 3. Assemble and Edit
audio_clip = AudioFileClip(AUDIO_FILE)
video_clip = VideoFileClip(bg_video_path)

# Cut asset to match voiceover timing
video_clip = video_clip.subclip(0, audio_clip.duration)

try:
    subtitle_text = "Watch until the end for a life lesson..."
    subtitle = TextClip(subtitle_text, fontsize=28, color='white', font='Arial', 
                        method='caption', size=(video_clip.w - 40, None), bg_color='black')
    subtitle = subtitle.set_pos('center').set_duration(audio_clip.duration)
    final_video = CompositeVideoClip([video_clip, subtitle]).set_audio(audio_clip)
except Exception as e:
    final_video = video_clip.set_audio(audio_clip)

OUTPUT_PATH = os.path.join(OUTPUT_FOLDER, "ready_to_upload.mp4")
final_video.write_videofile(OUTPUT_PATH, fps=24, codec="libx264", audio_codec="aac")
print(f"✅ Master Video Saved: {OUTPUT_PATH}")

# Clean up temp file
if os.path.exists("temp_bg.mp4"):
    os.remove("temp_bg.mp4")
    
